server:
  port: 9090
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/LPMS?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD:YourStrongRedisPassword123}
      database: 1
      timeout: 10000
      client-type: lettuce
      connect-timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
          time-between-eviction-runs: 10s
        shutdown-timeout: 100ms
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:}
    connection-timeout: 5s
    socket-timeout: 60s

minio:
  endpoint: minio:9000
  rootUser: ${MINIO_ROOT_USER:minioadmin}
  rootPassword: ${MINIO_ROOT_PASSWORD:minioadmin}
  bucketName: lpms

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.lawdoc: INFO

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl 